# Generated by Django 2.0.3 on 2018-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('proxy_host', models.CharField(blank=True, max_length=200)),
                ('root_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
