# Generated by Django 2.0.3 on 2018-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
