# Generated by Django 2.0.3 on 2018-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20180424_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=200, unique=True)),
                ('proxy_host', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
