# Generated by Django 2.0.3 on 2018-05-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='tls',
            field=models.BooleanField(default=True),
        ),
    ]
